apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
data:
  # TODO template this fields
  username: dGVzdAo= #root
  password: dGVzdAo= #root
  database: Zm9ya2RlbHRhCg== #forkdelta
