apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    app: forkdelta
    component: websocket
spec:
  ports:
  - port: 8080
    name: ws
  selector:
    app: forkdelta
    component: websocket